name: Build docker images
on:
  workflow_dispatch:
  schedule:
    - cron: '6 9 * * SUN'

jobs:
  ci-image:
    name: Build images for CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Buster build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/buster-build.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yeti-web/build-image:buster

      - name: Push Bullseye build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/bullseye-build.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yeti-web/build-image:bullseye

      - name: Push db image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/pg13.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yeti-web/pgsql:13
