name: Nigthly packages build

on:
  push:
    branches: [ master ]

jobs:
  deb10:
    name: Debian 10 nightly package building
    runs-on: ubuntu-latest
    container: switchyeti/yeti-web:buster-build
    services:
      db:
        image: switchyeti/yeti-web:pg13

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build package
        run: make package
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432

      - name: Display structure
        run: ls -R /__w

      - name: Save deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: /__w/yeti-web/*.deb

      - name: Upload package to ${{github.ref}} repo
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
        run: ci/deploy.sh buster nightly main ../*.deb

  deb10_container:
    name: Debian 10 container
    needs: deb10
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: deb-package

      - name: Display structure of downloaded files
        run: ls -R

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ci/nightly-package.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my-docker-hub-namespace/my-docker-hub-repository
          tag_with_ref: true

