name: Nigthly packages build

on:
  push:
    branches: [ master ]

jobs:
  deb10:
    name: Debian 10 nightly package building
    runs-on: ubuntu-latest
    container: ghcr.io/yeti-switch/yeti-web/build-image:buster
    services:
      db:
        image: ghcr.io/yeti-switch/yeti-web/pgsql:13

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build package
        run: make package
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432

      - name: Save deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb10-package
          path: /__w/yeti-web/*.deb

      - name: Upload package to ${{github.ref}} repo
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
        run: ci/deploy.sh buster nightly main ../*.deb

  deb11:
    name: Debian 11 nightly package building
    runs-on: ubuntu-latest
    container: ghcr.io/yeti-switch/yeti-web/build-image:bullseye
    services:
      db:
        image: ghcr.io/yeti-switch/yeti-web/pgsql:13

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build package
        run: make package
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432

      - name: Save deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb11-package
          path: /__w/yeti-web/*.deb

      - name: Upload package to ${{github.ref}} repo
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
        run: ci/deploy.sh bullseye nightly main ../*.deb

  deb11_container:
    name: Debian 11 container
    needs: deb11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: deb11-package

      - name: Display structure of downloaded files
        run: ls -la

      - name: Display path
        run: pwd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/nightly-package.Dockerfile
          push: true
          tags: ghcr.io/yeti-switch/yeti-web:nightly-build


