name: Release process

on:
  release:
    types: [ published ]

jobs:
  deb10:
    name: Debian 10 release package building
    runs-on: ubuntu-latest
    container: switchyeti/yeti-web:buster-build
    services:
      db:
        image: switchyeti/yeti-web:pg13

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build package
        run: make package
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432
      - name: Upload package to ${{github.ref}} repo
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
          PKG_TAG: ${{github.ref}} 
        run: v=${PKG_TAG##*/};major_version=${v%\.[0-9]*};ci/deploy.sh buster $major_version main ../*.deb
      - name: Create Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: ${{secrets.SENTRY_URL}}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_ORG: ${{secrets.SENTRY_ORG}}
          SENTRY_PROJECT:  ${{secrets.SENTRY_PROJECT}}
          SENTRY_LOG_LEVEL: "debug"
        with:
          version: ${{github.ref}}

